name: Remote Trigger Crawl

on:
  repository_dispatch:
    types: [trigger_crawl]

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create credentials file
        run: |
          echo '${{ secrets.CREDS_JSON }}' > vivid-layout-492502-m1-ec6b14b41e28.json

      - name: Run Script
        env:
          MISSIVE_API_KEY: ${{ secrets.MISSIVE_API_KEY }}
          LINKEDIN_USER: ${{ secrets.LINKEDIN_USER }}
          LINKEDIN_PASS: ${{ secrets.LINKEDIN_PASS }}
          LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}
        run: |
          xvfb-run -a python Crawl_LinkedIn_Profiles_2.py
      - name: Upload Screenshots
        if: always()                    # Luôn upload dù thành công hay lỗi
        uses: actions/upload-artifact@v4
        with:
          name: linkedin-screenshots
          path: ./*.png
          retention-days: 7
