name: Remote Trigger Crawl

on:
  repository_dispatch:
    types: [trigger-crawl] # Tên sự kiện mà cron-job.org sẽ gọi

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup Chrome Browser
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-chromedriver: true
      - name: Create credentials file
        run: |
            echo '${{ secrets.CREDS_JSON }}' > vivid-layout-492502-m1-ec6b14b41e28.json
        
      - name: Run Script
        env:
          LINKEDIN_USER: ${{ secrets.LINKEDIN_USER }}
          LINKEDIN_PASS: ${{ secrets.LINKEDIN_PASS }}
          LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }} # THÊM DÒNG NÀY
          CREDS_JSON: ${{ secrets.CREDS_JSON }}
        run: python "Crawl_LinkedIn_Profiles_2.py"
