name: Remote Trigger Crawl

on:
  repository_dispatch:
    types: [trigger-crawl] # Tên sự kiện mà cron-job.org sẽ gọi

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Create credentials file
        run: |
            echo '${{ secrets.CREDS_JSON }}' > vivid-layout-492502-m1-0bf0fc77aeb4.json
        
      - name: Run Script
        env:
          LINKEDIN_USER: ${{ secrets.LINKEDIN_USER }}
          LINKEDIN_PASS: ${{ secrets.LINKEDIN_PASS }}
        run: python "Task thục tập/Crawl_LinkedIn_Profiles_2.py"
